# brew tap Homebrew/brewdler ; has to come first.

# Taps
tap "homebrew/dupes"
tap "homebrew/versions"
tap "homebrew/fuse"
tap "caskroom/cask"
tap "rogual/neovim-dot-app"
tap "neovim/neovim"
tap "railwaycat/emacsmacport"

# Cask
brew "brew-cask"

# Build tools
brew "cmake"

# Dev tools
brew "android-platform-tools"
brew "heroku-toolbelt"
brew "mozilla-addon-sdk"
brew "awscli"
brew "gdb"

# Git
brew "hub"
brew "hubflow"
brew "git"
brew "git-flow"

# Libraries
brew "msgpack"
brew "libxml2"
brew "libyaml"
brew "openssl"

# Languages
brew "pypy"
brew "python"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python3"
brew "go"
brew "leiningen"
brew "node"

# Dev tools
brew "tmux"
brew "vim"
brew "macvim"
brew "emacs-mac"
# brew "emacs", args: ['with-cocoa', 'with-gnutls', 'srgb']
brew "neovim", args: ['HEAD']
brew "wget"
brew "reattach-to-user-namespace"
brew "watch"
brew "readline"
brew "zsh"
brew "zsh-lovers"
brew "tree"
brew "z"
brew "ag"
brew "ack"
brew "neovim-dot-app", args: ['HEAD']

# Misc tools
cask "osxfuse"
brew "ntfs-3g"

# General Apps
cask "skype"
cask "slack"

cask "google-chrome"
cask "1password"
cask "dropbox"

cask "sourcetree"
cask "little-snitch"

cask "iterm2"
cask "sublime-text3"
cask "intellij-idea"

cask "alfred"
cask "launchbar"

cask "shortcat"
cask "apptivate"
cask "hyperdock"
cask "hyperswitch"
cask "totalspaces"

cask "google-japanese-ime"

cask "asepsis"
cask "java6"