tap "mas-cli/tap", pin: true
brew "mas"

# Dev tools
brew "heroku-toolbelt"
cask "google-cloud-sdk"
cask "docker"

# Languages
brew "python"
brew "python3"
brew "go"
brew "clojure"
brew "leiningen"
brew "node"
brew "elixir"

# Dev tools
brew "openssl"
brew "ffmpeg"
cask "gpg-suite"
brew "coreutils"
brew "tmux"
brew "neovim"
brew "wget"
brew "reattach-to-user-namespace"
brew "watch"
brew "readline"
brew "z"
brew "ag"
brew "ack"
brew "fzf"
brew "gnu-sed"
brew "git"
brew "hub"

# Quicklook plugins
# https://github.com/sindresorhus/quick-look-plugins
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
cask "qlimagesize"
cask "webpquicklook"
cask "suspicious-package"
cask "quicklookase"
cask "qlvideo"

# Misc tools
cask "osxfuse"
brew "ntfs-3g"
brew "hardlink-osx"
mas "The Unarchiver", id: 425424353
brew "youtube-dl"

# Dev Apps
cask "gitup"
cask "little-snitch"
cask "kitty"
cask "sublime-text"
cask "vimr"
cask "dash"
mas "Xcode", id: 497799835

# Automation // Productivity
cask "keyboard-maestro"
cask "alfred"
cask "hyperswitch"
mas "Magnet", id: 441258766

# General Apps
cask "slack"
cask "transmission"
cask "anki"
cask "google-japanese-ime"
cask "1password"
cask "dropbox"
cask "bartender"
cask "beamer"
cask "airserver"
mas "Day One", id: 1055511498
mas "KakaoTalk", id: 869223134
mas "LINE", id: 539883307
mas "Reeder", id: 880001334
mas "Unsplash Wallpapers", id: 1284863847
