* David's dotfiles

To install all of these, just run ~./install.sh~. This assumes that your dotfiles are inside =~/.dotfiles/=

** brew
Apps and stuff that should be installed through brew (and cask) on all of my systems. To install, use [[https://github.com/Homebrew/homebrew-bundle][brew-bundle]].

** git
holds gitconfig and gitignore_global. Sets default editor, author name, credential helper and other stuff for git usage. Needs to get symlinked to =~/.gitconfig=  and =~/.gitignore_global=.

** pip
Basic python packages that have to be OS global and not virtualenv specific. Install with ~pip install -r packages.txt~

** npm
Same as pip but for node packages. Run ~python install.py~

** tmux
Adds tmux configuration to work with vim-friendly shorcuts and a better style. Comment the last line inside ~.tmux.conf~ in to use vim-tmuxline instead. Has to go under =~/.tmux.conf=

Also adds a terminfo file for adding italic font support to tmux

** vim
Awesome vim config you should try out. Put it (and .gvimrc, .ideavimrc) under =~/.vimrc=,  =~/.gvimrc= and =~/.ideavimrc=. Install plugins with [[https://github.com/VundleVim/Vundle.vim][Vundle]].

** spacemacs
My spacemacs config. Heavily opinionated. [[https://github.com/syl20bnr/spacemacs][Install spacemacs here.]] and symlink to =~/.spacemacs=.

** sublimious / sublime text
Config is managed by [[https://github.com/dvcrn/sublimious][sublimious]]. Symlink to =~/.sublimious= and install sublimious through package control.

** proton / atom
Config is managed by [[https://github.com/dvcrn/proton][proton]]. Symlink to =~/.proton= and install proton through apm.


** kwm
config for [[kwm][https://github.com/koekeishiya/kwm]]. Symlink to =~/.kwm/kwmrc=

** fisherman
experimental fishshell config based on [[fisherman][https://github.com/fisherman/fisherman]]. Symlink entire folder to =~/.config/fisherman= and install fisherman.

** peco
config for peco search. Symlink the config into =~/.config/peco/config.json=
*
** term
terminfo files for adding italic font support to xterm
