- name: github_copilot/gpt-3.5-turbo
  weak_model_name: gpt-4o-mini
  reminder: sys
  extra_params:
    max_tokens: 4096
    max_input_tokens: 32000
    max_output_tokens: 4096
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/gpt-4
  edit_format: udiff
  weak_model_name: gpt-4o-mini
  use_repo_map: true
  lazy: true
  reminder: sys
  extra_params:
    max_tokens: 4096
    max_input_tokens: 32768
    max_output_tokens: 4096
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/gpt-4.1
  edit_format: diff
  weak_model_name: github_copilot/gpt-4.1-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: gpt-4.1
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  extra_params:
    # max_tokens usually refers to max_output_tokens for aider
    max_tokens: 16384
    # Based on JSON: "max_prompt_tokens": 64000
    max_input_tokens: 64000
    # Based on JSON: "max_output_tokens": 16384
    max_output_tokens: 16384
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/gpt-4.5
  edit_format: diff
  weak_model_name: github_copilot/gpt-4.1-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: gpt-4.5-preview
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  extra_params:
    max_tokens: 32768
    max_input_tokens: 128000
    max_output_tokens: 32768
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/gpt-4o
  edit_format: diff
  weak_model_name: github_copilot/gpt-4o-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: gpt-4o
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  extra_params:
    max_tokens: 4096
    max_input_tokens: 128000
    max_output_tokens: 4096
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/gpt-4o-mini
  weak_model_name: github_copilot/gpt-4o-mini
  lazy: true
  reminder: sys
  extra_params:
    max_tokens: 4096
    max_input_tokens: 128000
    max_output_tokens: 4096
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/o1-ga
  edit_format: diff
  weak_model_name: github_copilot/gpt-4o-mini
  use_repo_map: true
  use_temperature: false
  streaming: false
  editor_model_name: gpt-4o
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  extra_params:
    max_tokens: 16384
    max_input_tokens: 128000
    max_output_tokens: 16384
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/o4-mini
  edit_format: diff
  weak_model_name: github_copilot/gpt-4.1-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: github_copilot/gpt-4.1
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  extra_params:
    max_tokens: 128000
    max_input_tokens: 128000
    max_output_tokens: 128000
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/o3-mini
  edit_format: diff
  weak_model_name: github_copilot/gpt-4o-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: github_copilot/gpt-4o
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  extra_params:
    max_tokens: 64000
    max_input_tokens: 128000
    max_output_tokens: 64000
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/o3
  edit_format: diff
  weak_model_name: github_copilot/gpt-4o-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: github_copilot/gpt-4o
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  extra_params:
    max_tokens: 64000
    max_input_tokens: 128000
    max_output_tokens: 64000
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/claude-3.5-sonnet
  edit_format: diff
  weak_model_name: github_copilot/claude-3.5-haiku
  use_repo_map: true
  examples_as_sys_msg: true
  cache_control: true
  editor_model_name: github_copilot/claude-3.5-sonnet
  editor_edit_format: editor-diff
  extra_params:
    max_tokens: 8192
    max_input_tokens: 128000
    max_output_tokens: 8192
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/claude-3.7-sonnet
  edit_format: diff
  weak_model_name: github_copilot/claude-3.5-sonnet
  use_repo_map: true
  examples_as_sys_msg: true
  cache_control: true
  editor_model_name: github_copilot/claude-3.7-sonnet
  editor_edit_format: editor-diff
  extra_params:
    max_tokens: 128000
    max_input_tokens: 128000
    max_output_tokens: 128000
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/claude-3.7-sonnet-thought
  edit_format: diff
  weak_model_name: github_copilot/claude-3.7-sonnet
  use_repo_map: true
  examples_as_sys_msg: true
  cache_control: true
  editor_model_name: github_copilot/claude-3.7-sonnet-thought
  editor_edit_format: editor-diff
  extra_params:
    max_tokens: 90000
    max_input_tokens: 128000
    max_output_tokens: 90000
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/gemini-2.0-flash
  edit_format: diff
  use_repo_map: true
  extra_params:
    max_tokens: 128000
    max_input_tokens: 128000
    max_output_tokens: 128000
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat

- name: github_copilot/gemini-2.5-pro
  edit_format: diff-fenced
  use_repo_map: true
  extra_params:
    max_tokens: 128000
    max_input_tokens: 128000
    max_output_tokens: 128000
    extra_headers:
      editor-version: Neovim/0.9.0
      Copilot-Integration-Id: vscode-chat
